/* eslint-disable react/no-unescaped-entities */
export const faqs = [
  {
    title: 'Basic Info',
    rows: [
      {
        title:
          'Why would I invest in tokenized plants instead of investing in shares of publicly traded or even private companies?',
        content: (
          <>
            By investing in tokenized plants (Treesury Trees or Tokens), you can
            invest with as little as $110 instantly, without the need for
            old-fashioned brokers, high associated fees, or expertise in the
            sector.
            <br />
            <br />
            Investments in agriculture are commonly reserved for high-net-worth
            individuals, agriculture industry specialists, private equity firms
            or institutional investors who can invest by buying shares in
            privately owned farming businesses through direct negotiations. Such
            negotiations take 12 to 18 months to complete and require
            substantial capital.
            <br />
            <br />
            Investing in Exchange-Traded Funds (ETF) from publicly listed
            companies offers a quicker, more accessible route to agriculture
            investment. These funds are however often diversified, meaning that
            only a proportion of the portfolio comprises agriculture. The rest
            will often be made up of other vertically integrated industries
            creating a detachment from the focus on return from agriculture.
            Distribution of dividends usually favors large shareholders’
            interests rather than the interests of all investors. As a result,
            profits may be retained for years, restricting all
            shareholders&apos; ability to receive income sooner.
          </>
        ),
      },
      {
        title: 'Why hazelnuts?',
        content: (
          <>
            Historically, hazelnut demand has exceeded supply, and with steady,
            expected, further growth in demand, market price is expected to
            continue its positive trend. Such growth is caused not only by the
            global rise in demand for food, but also because of change in
            consumer behavior - higher demand for alternative sources of
            proteins and healthier diet. Unlike other produce the price of
            hazelnuts does not fluctuate throughout the year. 90% of demand for
            hazelnuts is generated by the confectionery and bakery industries
            which also happen to be Treesury’s main buyers.
            <br />
            <br />
            Hazelnut trees are resistant to adverse weather conditions, pests
            and diseases, and independent of bees as they are wind pollinated.
            The long planting season allows flexibility for a longer
            crowdfunding period. Additionally, shelled hazelnuts can be easily
            stored for up to two years and losses during transportation are
            minimal, limiting the risk of stock perishability. The high level of
            mechanization and automation in hazelnut growing reduces required
            labor inputs which are 10x to 15x lower compared to apple and
            blueberry growing, respectively. With a labor shortage in the
            agriculture sector, lower labor requirements constitute a
            considerable advantage. Finally, hazelnuts require only a fraction
            of chemical treatments compared to other crops, i.e., apples require
            5x and blueberries 2x the number of chemical treatments.
            <br />
            <br />
            Nuts also have a negative carbon emissions figure in terms of land
            use because nut trees are currently replacing croplands; carbon is
            stored in the trees.
            <br />
            <br />
            <div className="treesuryTable-container">
              <div className="treesuryTable-responsive">
                <div className="treesuryTable table">
                  <div className="treesury-table">
                    <div className="treesury-table-titles">
                      <div className="title-row active">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">Parameters</div>
                      </div>
                      <div className="title-row" data-row="8">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">
                          Hail protection net required
                        </div>
                      </div>
                      <div className="title-row" data-row="7">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">First Yield (Years)</div>
                      </div>
                      <div className="title-row" data-row="6">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">Full Yield (Years)</div>
                      </div>
                      <div className="title-row" data-row="5">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">
                          Farm Lifespan (Years)
                        </div>
                      </div>
                      <div className="title-row" data-row="4">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">
                          Number of Standard Chemical Treatments
                        </div>
                      </div>
                      <div className="title-row" data-row="3">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">Harvesting Method</div>
                      </div>
                      <div className="title-row" data-row="2">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">
                          Labor: No. of hours per Year/ha (Without Harvest)
                        </div>
                      </div>
                      <div className="title-row" data-row="1">
                        <div className="line-bg"></div>
                        <div className="is-h6__title">
                          Harvesting: No. of hours per Year/ha
                        </div>
                      </div>
                    </div>
                    <div className="swiper" style={{ width: '100%' }}>
                      <div className="swiper-wrapper treesury-table-desktop">
                        <div
                          className="swiper-slide treesuryTableColumn treesury-table-column hovering"
                          data-column="treesury"
                        >
                          <div className="column-title">
                            <span>HAZELNUT</span>
                          </div>
                          <div className="column-value" data-row="8">
                            <span style={{ color: '#c7cb50' }}>No</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="7">
                            <span style={{ color: '#ff0000' }}>4-5</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="6">
                            <span style={{ color: '#ff0000' }}>9</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="5">
                            <span style={{ color: '#c7cb50' }}>40</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="4">
                            <span style={{ color: '#c7cb50' }}>4-5</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="3">
                            <span style={{ color: '#c7cb50' }}>Mechanical</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="2">
                            <span style={{ color: '#c7cb50' }}>78-86</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="1">
                            <span style={{ color: '#c7cb50' }}>28-35</span>
                            <div className="line-bg"></div>
                          </div>
                        </div>
                        <div
                          className="swiper-slide treesuryTableColumn treesury-table-column"
                          data-column="bonds"
                        >
                          <div className="column-title">
                            <span>APPLE</span>
                          </div>
                          <div className="column-value" data-row="8">
                            <span style={{ color: '#ff0000' }}>Yes</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="7">
                            <span style={{ color: '#c7cb50' }}>2</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="6">
                            <span style={{ color: '#c7cb50' }}>5</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="5">
                            <span>20</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="4">
                            <span>20-30</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="3">
                            <span>Manual</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="2">
                            <span>500-800</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="1">
                            <span>400-600</span>
                            <div className="line-bg"></div>
                          </div>
                        </div>
                        <div
                          className="swiper-slide treesuryTableColumn treesury-table-column"
                          data-column="stocks"
                        >
                          <div className="column-title">
                            <span>BLUEBERRY</span>
                          </div>
                          <div className="column-value" data-row="8">
                            <span color="#ff0000">Yes</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="7">
                            <span style={{ color: '#c7cb50' }}>2</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="6">
                            <span color="#c7cb50">5</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="5">
                            <span>30</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="4">
                            <span>6-10</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="3">
                            <span>Manual</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="2">
                            <span>200-400</span>
                            <div className="line-bg"></div>
                          </div>
                          <div className="column-value" data-row="1">
                            <span>1200-1500</span>
                            <div className="line-bg"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="faq-side-image">
                <img
                  src="assets/img/Environmental.png"
                  alt=""
                  className="img-fluid"
                />
              </div>
            </div>
          </>
        ),
      },
      {
        title: 'What are the size and dynamics of the hazelnut market?',
        content: (
          <>
            Over the past two decades, from 2002 to 2021, the hazelnut market
            has shown notable price fluctuations but with a clear positive
            trend. The recorded prices exhibit a range of values, with peaks and
            declines that reflect the dynamics of supply and demand in the
            industry. One significant peak occurred in 2014, which can be
            attributed to an unfavorable climate in Turkey, the largest hazelnut
            producer. This resulted in an extremely poor yield, causing a
            scarcity of hazelnuts and driving prices upward.
            <br />
            <br />
            <div
              style={{
                width: '100%',
                height: '500px',
                display: 'flex',
                justifyContent: 'center',
              }}
            >
              <canvas id="myChart"></canvas>
            </div>
            <br />
            <br />
            While a price correction was anticipated following the peak, the
            hazelnut market experienced a further decline in 2020. This decline
            can be attributed to the COVID-19 pandemic and subsequent lockdown
            measures, which heavily impacted the hospitality and wedding
            industries. These industries are major consumers of hazelnuts,
            particularly through the bakery sector. Despite the challenges posed
            by the pandemic, the price decline during this period was relatively
            small. Furthermore, the price rebounded in subsequent years,
            indicating resilience and an encouraging trend for the hazelnut
            market.
            <br />
            <br />
            The hazelnut market primarily serves industrial sectors, with
            approximately 55% of the supply directed towards the confectionery
            industry, 35% towards the bakery industry, and the remaining 10% for
            direct consumption. This emphasizes the significant role of
            hazelnuts in the production of various confectionery and bakery
            products. In addition to the quantitative deficit, the confectionery
            industry is often affected by the lack of high-quality hazelnuts, as
            only the best quality hazelnuts are used in confectionery
            production.
            <br />
            <br />
            <div
              style={{
                width: '100%',
                height: '500px',
                display: 'flex',
                justifyContent: 'center',
              }}
            >
              <canvas id="pieChart"></canvas>
            </div>
            <br />
            <br />
            Turkey holds a dominant position in the global hazelnut market,
            being the largest producer and processor of hazelnuts. Despite this,
            only a small percentage of hazelnut farms in Turkey (around 2%)
            utilize intensive cultivation methods with irrigation systems in
            place. This dependency on natural conditions makes Turkey's hazelnut
            production highly susceptible to climate variations and increases
            volatility in the market. Additionally, being susceptible to climate
            change, Turkey's hazelnut production also varies drastically in
            quality.
            <br />
            <br />
            Apart from Turkey, other notable hazelnut producers include Italy,
            Chile, USA, Azerbaijan, China, France, and Serbia. However, Turkey's
            market share ranges from 60% to 70% of the worldwide hazelnut
            production, highlighting its significant influence in the industry.
            Additionally, it is worth noting that a considerable portion (~25%)
            of the global hazelnut supply is consumed by Ferrero, a major
            confectionery company.
            <br />
            <br />
            In summary, the hazelnut market has experienced price fluctuations
            influenced by factors such as climate conditions, pandemic-related
            disruptions, and the demand from key industries. While Turkey
            dominates hazelnut production, other countries also contribute to
            the global supply. Understanding the dynamics of the hazelnut market
            is crucial for industry stakeholders, enabling them to navigate
            price volatility and capitalize on opportunities in this essential
            agricultural commodity.
            <br />
            <br />
            The hazelnut market is projected to expand significantly, with the
            global hazelnut market size valued at USD 12.62 billion in 2022. It
            is expected to grow at a CAGR of 9.14% during the forecast period,
            reaching USD 21.34 billion by 2028 (Source: marketwatch.com).
          </>
        ),
      },
      {
        title:
          'Does Treesury have hazelnut farming, harvesting and sales experience?',
        content: (
          <>
            Treesury’s Agri Specialists have over 20 years of international
            experience in hazelnut farming, processing and trade.
            <br />
            <br />
            The team has a track record of developing over 10,000ha of hazelnut
            farms, using proprietary farming methodology and technology that
            leverages artificial intelligence and machine learning for ultimate
            precision. As a result, they are able to achieve farm yields that
            are 30 to 50% higher than average, while automated hazelnut farming
            and harvesting reduces the risk of human error and labor costs, and
            solves the issue of labor shortage presently encountered in the
            industry.
            <br />
            <br />
            Additionally, by forging trusted relationships and leveraging their
            existing industry network, the Treesury team has managed to secure
            long term sales contracts for the sale of produce.
          </>
        ),
      },
      {
        title: 'Who can invest?',
        content: (
          <>
            Our current offering is marketed in the USA but we welcome investors
            from all geographies. You should, however, make sure that your
            country of residence does not impose any legal barriers.
            <br />
            <br />
            As Treesury complies with the USA sanctions, any investors that are
            on the sanctions list are not eligible to invest.
          </>
        ),
      },
      {
        title: 'Is there a minimum investment?',
        content: (
          <>
            You can start from as little as one Treesury Tree. Treesury gives
            everyone an opportunity to tap into large-scale agricultural
            projects that were once reserved for large investors only.
          </>
        ),
      },
      {
        title: 'Is there any upper limit to my potential investment?',
        content: (
          <>
            Treesury does not limit the number of trees you can purchase,
            however, seasonal limits may be put in place due to land
            availability and purchasing procedures, planting capacity, and
            timing of your purchase. We will do our best to communicate any such
            limits as soon as we become aware of them.
          </>
        ),
      },
      {
        title: 'What payment options do you accept?',
        content: (
          <>
            We accept all major credit cards and wire transfers. If your
            preferred payment method is not listed, please reach out to us and
            we will do our best to accommodate your request.
          </>
        ),
      },
      {
        title:
          'What is the difference between a Treesury Tree and a Treesury Token?',
        content: (
          <>
            One Treesury Token is equal to one Treesury Tree. Tokenization is
            only a tool that facilitates our business model.
          </>
        ),
      },
      {
        title: 'How do Treesury farms actually make money?',
        content: (
          <>
            Farms generate revenues by selling agricultural produce and carbon
            credits (once they are certified as a carbon credits generator or
            project developer).
          </>
        ),
      },
      {
        title: 'What exactly do I get by purchasing a Treesury Tree?',
        content: (
          <>
            You gain profit sharing rights with every purchased Treesury Tree.
            The share of profits you receive will be a pro-rata amount of your
            holding vs the total number of trees on the particular farm.
          </>
        ),
      },
    ],
  },

  {
    title: 'Returns, Monitoring & Payouts',
    rows: [
      {
        title:
          'Is the price of Treesury Trees affected by fluctuations in cryptocurrencies?',
        content: (
          <>
            No, the price of Treesury Trees is not influenced by
            cryptocurrencies in any way. Treesury Trees are security tokens and
            are not tied to the fluctuations of cryptocurrencies. Their value is
            determined by factors specific to the Treesury project and its
            underlying assets, such as the agricultural production and
            production of carbon credits. This independence from cryptocurrency
            fluctuations adds stability and predictability to Treesury tokens,
            making them an attractive investment option independent from the
            volatile cryptocurrency market.
          </>
        ),
      },
      {
        title: 'What are the factors affecting Treesury Tree prices and how?',
        content: (
          <>
            Each year, Treesury sets the price for initial offering of Treesury
            Trees based on a comprehensive evaluation. However, once the tokens
            enter the secondary market, their value is determined by the
            principles of supply and demand in the free market. The Treesury
            Tree derives its worth from the cash flow generated through the
            economic utilization of the tokenized asset, which is the hazelnut
            tree.
            <br />
            <br />
            Several factors can influence the token price, with the primary
            drivers being the revenues generated from the sale of hazelnut
            produce and carbon credits, as well as costs associated with the
            Treesury Tree's farm. Let's explore these factors and how they can
            affect the token's value:
            <br />
            <br />
            Hazelnut Market Prices: Fluctuations in hazelnut market prices can
            have a direct impact on the token value. Higher prices can increase
            revenues and potentially boost the token price, while lower prices
            can influence a decrease in the token price.
            <br />
            <br />
            Carbon Credit Market Prices: Following the same logic as hazelnut
            market prices, changes in environmental regulations and market
            demand can cause variations in the value of carbon credits. As
            carbon credits play a significant role in the token's cash flow,
            fluctuations in their price can impact the token value.
            <br />
            <br />
            Adoption of Greenhouse Gas/Carbon Offsetting Schemes: The increasing
            adoption of greenhouse gas and carbon offsetting schemes can drive
            the demand for carbon credits. This growing demand has the potential
            to positively affect the token value. Conversely, slower adoption
            may have an adverse impact on the tokens.
            <br />
            <br />
            Regulatory Requirements: Changes in regulations related to
            environmental sustainability, carbon emissions, or agricultural
            practices can influence the profitability of the hazelnut farm.
            Compliance with new regulations may lead to additional costs or
            operational adjustments, which can subsequently influence the token
            price. On the other hand, such regulations may significantly impact
            the demand for carbon offsets and consequently positively affect the
            price of carbon credits.
            <br />
            <br />
            Weather Conditions: Despite employing precision agriculture methods,
            hazelnut production is somewhat susceptible to weather patterns,
            including temperature, rainfall, and climate conditions. Adverse or
            favorable weather events can impact crop yield, which in turn
            affects revenues and ultimately influences the token value. To
            mitigate this risk, we provide insurance coverage for the yield.
            <br />
            <br />
            Economic Cycles: Economic cycles can influence consumer demand for
            hazelnuts and carbon credits, among other products. Different
            economic effects may lead to either favorable or adverse
            consequences for the token price, depending on their impact on the
            token's cash flow.
            <br />
            <br />
            It's important to note that during the early years of token
            issuance, early investors benefit from discounts offered by
            Treesury, which contribute to an initial boost in the token price on
            the secondary market. Additionally, investors enjoy full payback
            priority of their initial investment until Treesury starts to share
            in the profits. However, as the token's lifespan is tied to the
            economic exploitation of the hazelnut tree (40 years), the price may
            gradually decline over time.
            <br />
            <br />
            While we believe in the potential for capital gains due to the
            projected increase in Treesury Tree prices and the long-term
            opportunity for passive income through the profit-sharing scheme,
            it's essential to understand that investing in tokens carries
            inherent risks. The value of tokens can fluctuate, and past
            performance is not indicative of future results. Therefore, we
            strongly encourage investors to carefully evaluate the risks
            involved and conduct thorough research before making any investment
            decisions.
            <br />
            <br />
            Investing in Treesury Trees should be considered with the
            understanding that token prices can be influenced by a multitude of
            factors, both internal and external. While we have highlighted some
            of the key factors that can impact token value, it's important to
            note that there may be additional elements that can come into play.
            <br />
            <br />
            At Treesury, we are committed to providing transparency and offering
            an attractive investment opportunity. However, we cannot guarantee
            specific outcomes or the precise trajectory of token prices. The
            token market is subject to market forces and can be influenced by
            various economic, environmental, and regulatory factors that are
            beyond our control.
            <br />
            <br />
            By investing in Treesury Trees, investors have the opportunity to
            contribute to sustainable practices and participate in the growth of
            the agroforestry industry while potentially benefiting from capital
            gains and/or long-term passive income. Nevertheless, we strongly
            advise investors to consult with financial professionals, conduct
            their own research, and carefully assess their investment goals and
            risk tolerance.
            <br />
            <br />
            Please remember that this information is provided for informational
            purposes only and should not be considered as financial or
            investment advice. Each individual's financial situation is unique,
            and it's important to make investment decisions based on personal
            circumstances and consultation with qualified professionals.
            <br />
            <br />
            Together, we can create a greener future while recognizing the
            inherent uncertainties of the market and making informed investment
            choices.
            <div
              style={{
                width: '100%',
                height: '500px',
                display: 'flex',
                justifyContent: 'center',
              }}
            >
              <canvas id="YearsChart"></canvas>
            </div>
            <p className="disclaimer">
              * This projection is for a Year 1
              <br />
              The projected token value provided is based on current market
              analysis, trends, assumptions, and other relevant factors,
              specifically for the Year 1 - Early Bird Offering token. However,
              please note that projections are subject to inherent uncertainties
              and market volatility. The actual value of the tokens may vary and
              could be higher or lower than the projected value. Investments in
              tokens involve risks, and past performance is not indicative of
              future results. We advise investors to conduct their own research
              and exercise caution when making investment decisions.
            </p>
          </>
        ),
      },
      {
        title:
          'How can I make money with Treesury? What are the sources of returns from buying a Treesury tree?',
        content: (
          <>
            Investing in Treesury Trees is an opportunity for both capital
            growth via value of the Treesury Tree, and annual income through
            profit share rights. As the trees mature, their value appreciates,
            allowing investors to sell their rights at a higher price than that
            of the initial investment. The trees also generate annual income
            through both harvest profits and carbon credits, further expanding
            the potential for return. By purchasing a tree at its lowest price
            point, investors are able to maximize the future growth potential of
            their tree, allowing for the opportunity to reap a significant
            return over the long run.
          </>
        ),
      },

      {
        title: 'What is the potential ROI?',
        content: (
          <>
            Expected average annual yield rate, calculated over the project
            lifetime of 40 years is 12% to 15%. Therefore, Treesury could be a
            well-balanced and environmentally friendly solution for a long-term,
            recurring, passive income depending on your risk and holding
            appetite.
          </>
        ),
      },
      {
        title: 'Do you guarantee returns?',
        content: (
          <>
            All investments carry a degree of risk. Treesury Trees are no
            exception. Hazelnut trees are resistant to bad weather conditions,
            hazelnuts are a produce in high demand and agricultural investments
            show positive historical trends, however, the past is not a
            guarantee of the future. It is your responsibility to assess risks
            and any potential impact.
          </>
        ),
      },
      {
        title: 'What is the payback period for the purchased Treesury Trees?',
        content: (
          <>
            <div
              className="absolute -top-[73px] md:-top-[79px]"
              id="example-faq-item"
            ></div>
            Expected payback period is nine to ten years from planting the tree.
            Once Treesury becomes a certified carbon credits generator, and as
            obligatory and voluntary schemes for offsetting greenhouse gas
            emissions become mainstream, this period may shorten.
          </>
        ),
      },
      {
        title:
          'Nine to ten years is a rather long period to wait for the payback. Why does it take so long?',
        content: (
          <>
            Trees need several years to grow and develop properly in order to
            bear fruit. For hazelnuts, the first harvest is usually possible in
            year 4. The tree reaches maturity in year 9. From year 9, the tree
            could produce its maximum yield until year 40, significantly
            accelerating returns. Read more about potential ROI
            <a href="https://demo.treesury.com/#calculator" target="_blank">
              here
            </a>
            .
          </>
        ),
      },
      {
        title: 'How can I monitor my investment?',
        content: (
          <>
            All Treesury investors have access to the Treesury portal, where
            they can read reports about our operations, farm activities and
            analyses from Treesury Agri Specialists. In addition, they can
            access video footage from our farms or visit them in person.
            <br />
            <br />
            All in-person visits must be scheduled at least two weeks in advance
            so they can be coordinated around farm activities. Treesury
            investors can benefit from special rates at partnering hotels
            including Hyatt, Crown Plaza, Square 9, Falkensteiner, Saint Ten and
            Metropol, as well as restaurants, bars, travel agencies and car
            rentals. For more details and to book a farm visit please
            <a href="https://demo.treesury.com/#contact">contact us.</a>
          </>
        ),
      },
      {
        title:
          'What if I need my money back fast? Do you offer refunds? Can I sell my Treesury Trees?',
        content: (
          <>
            As Treesury Trees are security tokens, they cannot be refunded. You
            can, however, sell your Token(s) on the secondary market once
            Treesury Token is listed, or on the Treesury marketplace once
            available. One of the main advantages of the Treesury business model
            over a traditional agricultural investment is the access to a
            secondary market, which ensures investment liquidity. We aim to
            provide secondary market trading by H1 2024. Trading restrictions
            may apply, in accordance with the Securities Act of 1933. You can
            find more details on the timing on our
            <a href="/#roadmap" target="_blank">
              Roadmap.
            </a>
          </>
        ),
      },
      {
        title: 'Will Treesury charge farm management fees?',
        content: (
          <>There are no additional costs apart from the tree purchase price.</>
        ),
      },
      {
        title: 'How are profits shared between tree owners and Treesury?',
        content: (
          <>
            Only once you receive full return of your initial investment,
            Treesury will start to take a profit share of 50%.
          </>
        ),
      },
      {
        title: 'How will Treesury distribute profits?',
        content: (
          <>
            Profits are distributed once per year, pro-rata, based on the number
            of tokens held and the total number of Treesury Trees planted on any
            given farm. Because profits are pro-rata, should anything happen to
            your trees, you will still receive your payouts, and your trees will
            be replanted.
          </>
        ),
      },
      {
        title: ' How will I receive my payout?',
        content: (
          <>
            Following the sale of produce, the payout will be distributed to a
            bank account of your choosing. You can enter your banking
            information from your Treesury dashboard.
          </>
        ),
      },
      {
        title: 'When will I receive my payout?',
        content: (
          <>
            Payouts are made once a year, following the seasonal harvest. Once
            harvested, produce is sold to large supply chain buyers, with whom
            long-term term agreements for the supply of produce have been
            established. Payouts are based on pro-rata Treesury Tree holdings
            rather than on the particular tree yield, in order to minimize your
            risk.
          </>
        ),
      },
      {
        title: 'Is there a minimum payout threshold?',
        content: (
          <>
            Minimum payout threshold is $100. We introduced this threshold
            because of administrative and transaction costs.
          </>
        ),
      },
      {
        title: ' Can I reinvest my profits instead of getting a payout?',
        content: (
          <>
            Yes, you can always opt to reinvest your profits. All reinvestment
            requests are rounded to a single tree. Any excess value can be paid
            out to your bank account.
          </>
        ),
      },
      {
        title: 'Will I also receive returns from the sale of carbon credits?',
        content: (
          <>
            Eventually, payouts will be available for carbon credits sold.
            Certification of Treesury Trees for carbon credits is underway. As
            soon as Treesury becomes certified, Treesury investors will be
            eligible for a portion of profits from the credits sold. More
            details will be released upon certification.
          </>
        ),
      },
      {
        title: 'What is the potential return on carbon credits?',
        content: (
          <>
            Nuts are one of the few food produce supply chains that, with
            regards to carbon output, have not only the lowest land use carbon
            figure, but also a negative carbon rating, due to the fact that the
            trees store carbon from the atmosphere.
            <br />
            <br />
            Though carbon sequestration and carbon credits schemes are in their
            embryonic stage, the value of carbon sequestration could be worth
            between $47/ton to $120/ton by 2050 (Source: BloombergNEF), with the
            mean sequestration of a hazelnut orchard being 68t/ha a year. Data
            also shows an acceleration in the adoption of carbon credit programs
            with 1 in 4 organizations actively buying carbon removal solutions
            (Source: Circular Carbon Network – an Xprize initiative)
            <br />
            <br />
            Nature-derived carbon credit prices have increased by 173% in 2021
            in a global voluntary market valued at $1 billion (Source: S&P
            Global), with forestry credit transactions representing almost 67%
            of the total market. The total market size in 2022 is over $2
            billion (Source: ClimateTrade).
            <br />
            <br />
            <a href="https://demo.treesury.com/#calculator">
              Learn more using our interactive calculator
            </a>
          </>
        ),
      },
      {
        title: 'What is the math?',
        content: (
          <>
            <p>
              Produce Profit is worked out pro-rata per subject farm as follows:
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Produce Profit</b>=
            </p>
            <p className="text-center">
              <u>
                (farm produce revenue – farm costs) x (# Treesury Trees held on
                farm)
              </u>
            </p>
            <p className="text-center" style={{ fontSize: '75%' }}>
              Total number of Treesury Trees on farm
            </p>
            <p>&nbsp;</p>
            <p>
              Carbon Credit Profit is worked out based on the sale of carbon
              credits per subject farm as follows:
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Carbon Credits Profit</b> =
            </p>
            <p className="text-center">
              <u>
                (Carbon credits revenue – Carbon credit costs) x (# Treesury
                Trees held on the subject farm)
              </u>
            </p>
            <p className="text-center" style={{ fontSize: '75%' }}>
              Total number of Treesury Trees on farm
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Payout</b> = Produce Profit + Carbon Credits Profit
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Subject farm revenue from produce sales</b> = Total yield of
              subject farm x Produce sale price.
            </p>
          </>
        ),
      },
      {
        title: 'What are the costs of operating a subject farm?',
        content: (
          <>
            Main costs include cost of land, infrastructure and equipment,
            labor, fertilizers, irrigation, insurance, harvest, processing,
            storage, transportation, and any other costs incurred to produce and
            sell the hazelnuts. Customer care is also included.
          </>
        ),
      },
      {
        title: 'What costs are incurred in the sale of carbon credits?',
        content: (
          <>
            Costs include membership(s) in carbon credit organization(s) and
            schemes, relevant certifications and accreditations and related
            fees, and taxes paid to exchanges or government bodies. Cost of
            sales of carbon credits and customer care costs are also included.
          </>
        ),
      },
    ],
  },
  {
    title: 'Storing Your Tokens',
    rows: [
      {
        title: 'What document or proof of ownership do I get?',
        content: (
          <>
            You are buying a Treesury Tree which is a security token with an
            incorporated smart contract entitling you to profit sharing rights.
            Your Treesury Tree Token will be stored in your connected digital
            asset wallet.
          </>
        ),
      },
      {
        title: 'What is a Security Token Offering (STO)?',
        content: (
          <>
            Security Token Offerings (STO) are a digital representation of
            ownership in assets that work through automation and smart
            contracts. They combine the regulatory requirements of securities
            markets with the benefits of blockchain technology, promoting
            greater liquidity and access to capital.
          </>
        ),
      },
      {
        title: 'Why does Treesury use blockchain?',
        content: (
          <>
            Blockchain technology, which underpins Treesury's operations, is a
            key component of Web3, a more advanced and decentralized version of
            the internet compared to the older Web2.
            <br />
            <br />
            Web2 is the internet as we know it today, where information is
            largely centralized and controlled by a few big companies like
            Google, Facebook, Amazon, etc. In Web2, we depend on these
            centralized platforms to store our data, provide us with services,
            and facilitate transactions.
            <br />
            <br />
            Web3, on the other hand, is built on blockchain technology, which is
            decentralized and operates on a network of computers, making it more
            secure and resistant to hacking and fraud. With Web3, users can have
            more control over their data and can transact directly with each
            other without the need for intermediaries.
            <br />
            <br />
            In Treesury's case, using Web3 and blockchain technology allows us
            to operate a secondary market in a more efficient and secure way,
            compared to if we were operating solely on Web2. By using
            blockchain, Treesury can ensure that ownership of assets is
            transparent, tamper-proof, and can be easily verified. This makes it
            easier for buyers and sellers to transact, increasing the liquidity
            of Treesury's trees and making it a more attractive asset for
            investment.
          </>
        ),
      },
      {
        title: 'How long is the Treesury Token valid?',
        content: <> Validity of the token is 40 years.</>,
      },
      {
        title: 'What is a digital asset wallet?',
        content: (
          <>
            A digital asset wallet is a software used to communicate with
            blockchain networks to safely access, send and receive digital
            assets. Unlike fiat money (e.g. USD and Euro) digital assets are
            stored on the blockchain instead of the bank. Digital asset wallets
            store your private keys, keeping your assets safe and easily
            accessible. They also allow you to send and receive digital assets.
            These wallets come in many forms, from hardware wallets like Ledger
            (which looks like a USB stick) to mobile apps or websites, which
            makes using a wallet as easy as shopping with a credit card online.
          </>
        ),
      },

      {
        title:
          'What is the difference between Paper, Hardware and Online digital asset wallets?',
        content: (
          <>
            Digital asset wallets range from simple-to-use applications to more
            complex solutions. The main types of wallets you can choose from
            include:
            <br />
            <br />
            <i>Paper wallets:</i> Keys are written on a physical medium like
            paper and stored in a safe place. This wallet makes using your
            digital asset wallet harder because like digital money it can only
            be used on the internet.
            <br />
            <br />
            <i>Hardware wallets:</i> Keys are stored in a thumb-drive (USB)
            device that is kept in a safe place and only connected to a computer
            when you want to use your wallet.
            <br />
            <br />
            <i>Online wallets:</i> Keys are stored in a mobile application or
            website – We recommend ones that are protected by two-factor
            authentication. These wallets make sending, receiving, and using
            your wallet as easy as using any online bank account.
          </>
        ),
      },
      {
        title: 'Which digital asset wallet is good for me?',
        content: (
          <>
            We let everyone choose their own wallet. For convenience, we provide
            a list of a few popular wallets on the market: Ledger, Trezor,
            Republic, Coinbase, Exodus, Metamask, and ZenGo.
          </>
        ),
      },
    ],
  },
  {
    title: 'Treesury Farms',
    rows: [
      {
        title: ' Where are your farms located?',
        content: (
          <>
            Although Treesury is headquartered in the United States, the first
            farms and regional headquarters are located in Serbia.
          </>
        ),
      },
      {
        title: 'Why don’t you operate your farms in the United States?',
        content: (
          <>
            Climate conditions in South East Europe are optimal for hazelnut
            farming. Farmland is relatively competitive, numerous government
            subsidies are available, and wages are more competitive than in the
            US. These cost savings are passed on to tree investors when they
            purchase their Treesury Tree.
          </>
        ),
      },
      {
        title: 'Is my investment safe in Serbia?',
        content: (
          <>
            Investing in Serbia is generally considered safe due to several key
            factors that contribute to a stable and promising investment
            environment.
            <br />
            <br />
            Economic Stability: Serbia has shown resilience in its economic
            performance, maintaining stable GDP growth and fiscal discipline.
            The country's financial sector is well-regulated and has
            demonstrated resilience even during global economic challenges.
            <br />
            <br />
            EU Accession Process: Serbia is in the process of joining the
            European Union, a significant indicator of its commitment to
            political and economic reforms. This process drives the
            implementation of international standards and practices, enhancing
            transparency and reducing investment risks. Furthermore, this
            journey opens access to substantial EU pre-accession funds that hold
            the potential to drive progress and development.
            <br />
            <br />
            Foreign Direct Investment (FDI): Serbia has attracted notable FDI
            from various countries, showcasing investor confidence. The
            government actively promotes foreign investment through incentives
            such as tax breaks, grants, and streamlined administrative
            processes.
            <br />
            <br />
            Strategic Location: Serbia's geographical location is advantageous,
            positioned at the crossroads of major European markets. This
            strategic position facilitates trade and provides access to a wide
            consumer base.
            <br />
            <br />
            Skilled Workforce: The country has a well-educated workforce,
            particularly in fields like IT, engineering, and manufacturing. This
            talent pool contributes to a competitive advantage for industries
            that require skilled labor.
            <br />
            <br />
            Infrastructure Development: Serbia has invested in improving its
            infrastructure, including transportation and energy sectors. This
            enhances connectivity and lowers operational costs for businesses.
            <br />
            <br />
            Investor Protections: Serbia offers legal protection for investors,
            including guarantees against nationalization and expropriation.
            Bilateral investment treaties provide additional safeguards.
            <br />
            <br />
            Growing Sectors: Serbia's IT, agriculture, manufacturing and
            renewable energy sectors are witnessing substantial growth,
            presenting diverse investment opportunities.
            <br />
            <br />
            Major US Investments: Prominent US companies like Microsoft, NCR,
            and Ball Packaging have made significant investments, reflecting the
            confidence in the country's potential.
            <br />
            <br />
            Government Reforms: The Serbian government has undertaken reforms to
            improve the business climate, reduce bureaucracy, and enhance
            transparency.
            <br />
            <br />
            International Recognition: In the summer of 2023, after four rounds
            of voting and intense competition, the Member States of the Bureau
            International des Expositions (BIE) elected Serbia as the host
            country for Specialized Expo 2027. Serbia emerged victorious among
            five contenders, which included the USA, Thailand, Spain, and
            Argentina.
          </>
        ),
      },
      {
        title:
          'What are the advantages of investing in Serbia for US investors, and how does Serbia mitigate potential risks for foreign investors?',
        content: (
          <>
            Investing in Serbia presents a compelling opportunity for US
            investors due to several factors that mitigate risk and foster
            economic growth. Serbia's political stability, strategic location,
            and pro-business environment are key factors that attract
            international investors.
            <br />
            <br />
            Serbia boasts a stable political landscape, having transitioned into
            a democratic state. This stability creates a favorable environment
            for long-term investments, minimizing potential disruptions.
            Additionally, its strategic location at the crossroads of Europe
            offers access to diverse markets, making it an attractive hub for
            trade and investment.
            <br />
            <br />
            Furthermore, Serbia has taken significant steps to create a
            pro-business environment. The government has implemented reforms to
            simplify regulatory processes, reduce bureaucracy, and encourage
            foreign direct investment (FDI). The recently introduced Investment
            Promotion Act provides various incentives to investors, including
            tax breaks, land concessions, and grants.
            <br />
            <br />
            In terms of risk mitigation, Serbia leads the region in FDI, a
            testament to its attractiveness as an investment destination. Major
            US companies have recognized Serbia's potential and made substantial
            investments. For instance, Microsoft has established a development
            center, NCR has invested in a software hub, and Ball Packaging has
            built a production facility. These investments demonstrate the
            confidence in Serbia's business climate and growth prospects.
            <br />
            <br />
            Microsoft's Development Center, for example, has contributed to
            Serbia's emergence as a technology hub. Moreover, NCR's software hub
            has played a pivotal role in advancing the IT sector. Ball
            Packaging's investment has bolstered the manufacturing industry,
            creating job opportunities and economic growth.
            <br />
            <br />
            Investors in Serbian projects can significantly benefit from the
            country's alignment with the EU's Instrument for Pre-accession
            Assistance (IPA). With a substantial budget of €14.162 billion for
            2021-2027, IPA III offers opportunities for modernization,
            heightened competitiveness, and sustainable practices. These funds
            enable businesses to leverage advanced infrastructure, technology,
            and innovation, thereby reducing investment and operational costs.
            <br />
            <br />
            Serbia's ongoing efforts to improve its infrastructure, education
            system, and innovation ecosystem further enhance its appeal to
            investors.
            <br />
            <br />
            In conclusion, investing in Serbia offers a favorable risk-reward
            profile for US investors. The nation's political stability,
            strategic location, pro-business policies, and success in attracting
            major US companies make it an alluring investment destination. While
            careful assessment and understanding of the local market are
            essential, Serbia's growing economy and commitment to creating an
            investor-friendly environment make it a promising destination for
            those seeking diversification and growth opportunities.
          </>
        ),
      },
      {
        title:
          'If I decide to purchase Treesury Trees, when will you plant them?',
        content: (
          <>
            Trees are planted in the first planting cycle following purchase.
            The planting season starts in October and ends in March. Precise
            planting timing depends on weather conditions and the total number
            of Treesury Trees sold for the season.
          </>
        ),
      },
      {
        title: "What is the tree's lifetime?",
        content: (
          <>
            Economical lifetime of Treesury trees is 40 years after being
            planted.
          </>
        ),
      },
      {
        title: 'What happens if my tree withers?',
        content: (
          <>
            All Treesury Trees come with a two-year replanting guarantee. Should
            a tree wither, it will be replanted at no cost as soon as
            practically possible. Your payout will not be affected as your tree
            will still count for profit distribution. After expiration of the
            guarantee period, any replanting costs will count as direct farm
            maintenance costs.
          </>
        ),
      },

      {
        title: 'How likely will a tree wither?',
        content: (
          <>
            Based on our 20+ years long experience, this happens to less than 1%
            of the trees we plant.
          </>
        ),
      },
      {
        title:
          'What happens in case of any unforeseen circumstances: a storm, extreme drought or similar?',
        content: (
          <>
            Treesury farms are fully insured. Any possible settlements would be
            paid out to investors using the same logic applied to profit
            sharing.
          </>
        ),
      },
      {
        title:
          'What exactly do you mean by smart or data-driven precision farming that you use on your farms?',
        content: (
          <>
            In order to increase productivity and efficiency, and ensure
            transparency in the production, as well as to keep the token-holders
            informed, we monitor the production with a wide range of digital
            technologies including sensors (soil moisture, weather, NDVI…),
            Sentinel-2 satellite imaging (multispectral imaging and vegetation
            indices) and drone imagery. Automated soil composition lab testing
            is also used. All this data is used in real-time or near real-time
            by our machine learning algorithms and expert agronomists, and
            serves as a valuable piece of information for optimization of
            decision-making on the field. This data will also be used in our
            operational reports to token investors.
          </>
        ),
      },
      {
        title:
          ' How do you make sure your operations are sustainable and environmentally friendly?',
        content: (
          <>
            Our core activity is planting trees, which then sequester CO2, hence
            our operations are environmentally friendly in their essence. We
            also implement sustainability measures like utilizing pruned
            branches and hazelnut shells for energy production, and regenerative
            agriculture practices such as planting cover crops between the farm
            rows, in order to maintain soil quality and reduce excessive heat in
            the summer, resulting in less water consumption. We use precision
            agriculture practices based on sensor data, satellite and drone
            imagery, and laboratory analysis. These methods allow us to limit
            and optimize the amount of chemicals and water used in our
            agricultural production. Additionally, we use natural fertilizers
            whenever possible. All these measures are integrated into our
            proprietary hazelnut growing methodology. Therefore, sustainability
            is engraved in Treesury’s DNA
          </>
        ),
      },
    ],
  },
]
